// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: discovery_history.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteDiscoveryHistory = `-- name: DeleteDiscoveryHistory :execrows
DELETE FROM discovery_history
WHERE user_id = $1 AND media_id = $2
`

type DeleteDiscoveryHistoryParams struct {
	UserID  uuid.UUID
	MediaID uuid.UUID
}

func (q *Queries) DeleteDiscoveryHistory(ctx context.Context, arg DeleteDiscoveryHistoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDiscoveryHistory, arg.UserID, arg.MediaID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDiscoveryHistoryExpiry = `-- name: GetDiscoveryHistoryExpiry :one
SELECT next_eligible_at
FROM discovery_history
WHERE user_id = $1 AND media_id = $2
`

type GetDiscoveryHistoryExpiryParams struct {
	UserID  uuid.UUID
	MediaID uuid.UUID
}

func (q *Queries) GetDiscoveryHistoryExpiry(ctx context.Context, arg GetDiscoveryHistoryExpiryParams) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getDiscoveryHistoryExpiry, arg.UserID, arg.MediaID)
	var next_eligible_at time.Time
	err := row.Scan(&next_eligible_at)
	return next_eligible_at, err
}

const setDiscoveryHistoryExpiry = `-- name: SetDiscoveryHistoryExpiry :exec
INSERT INTO discovery_history (user_id, media_id, next_eligible_at) 
VALUES ($1, $2, $3)
ON CONFLICT (user_id, media_id)
DO UPDATE SET
  next_eligible_at = EXCLUDED.next_eligible_at
`

type SetDiscoveryHistoryExpiryParams struct {
	UserID         uuid.UUID
	MediaID        uuid.UUID
	NextEligibleAt time.Time
}

func (q *Queries) SetDiscoveryHistoryExpiry(ctx context.Context, arg SetDiscoveryHistoryExpiryParams) error {
	_, err := q.db.ExecContext(ctx, setDiscoveryHistoryExpiry, arg.UserID, arg.MediaID, arg.NextEligibleAt)
	return err
}
