// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package database

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (
  created_at, 
  updated_at, 
  tmdb_id, 
  title, 
  original_title, 
  poster_path, 
  backdrop_path, 
  overview, 
  release_date, 
  runtime, 
  media_type
) 
VALUES (
  NOW(), NOW(), $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, created_at, updated_at, tmdb_id, title, original_title, poster_path, backdrop_path, overview, release_date, runtime, media_type
`

type CreateMediaParams struct {
	TmdbID        int32
	Title         string
	OriginalTitle string
	PosterPath    string
	BackdropPath  string
	Overview      string
	ReleaseDate   time.Time
	Runtime       int32
	MediaType     string
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRowContext(ctx, createMedia,
		arg.TmdbID,
		arg.Title,
		arg.OriginalTitle,
		arg.PosterPath,
		arg.BackdropPath,
		arg.Overview,
		arg.ReleaseDate,
		arg.Runtime,
		arg.MediaType,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TmdbID,
		&i.Title,
		&i.OriginalTitle,
		&i.PosterPath,
		&i.BackdropPath,
		&i.Overview,
		&i.ReleaseDate,
		&i.Runtime,
		&i.MediaType,
	)
	return i, err
}

const createMediaGenre = `-- name: CreateMediaGenre :exec
INSERT INTO media_genres (
    created_at,
    genre_id,
    media_id
) VALUES (
    NOW(), $1, $2
)
`

type CreateMediaGenreParams struct {
	GenreID uuid.UUID
	MediaID uuid.UUID
}

func (q *Queries) CreateMediaGenre(ctx context.Context, arg CreateMediaGenreParams) error {
	_, err := q.db.ExecContext(ctx, createMediaGenre, arg.GenreID, arg.MediaID)
	return err
}

const getAllMedia = `-- name: GetAllMedia :many
SELECT id
FROM media
`

func (q *Queries) GetAllMedia(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getAllMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGenre = `-- name: GetGenre :one
SELECT id
FROM genres
WHERE name = $1
`

func (q *Queries) GetGenre(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getGenre, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getMedia = `-- name: GetMedia :one

SELECT  media.id,
        media.tmdb_id,
        media.title,
        media.original_title,
        media.poster_path,
        media.backdrop_path,
        media.overview,
        media.release_date,
        media.runtime,
        media.media_type,
        COALESCE((
            SELECT json_agg(genres.name)
            FROM genres
            JOIN media_genres ON genres.id = media_genres.genre_id
            WHERE media_genres.media_id = media.id
        ), '[]'::json) AS genres
FROM media
WHERE media.tmdb_id = $1 AND media.media_type = $2
`

type GetMediaParams struct {
	TmdbID    int32
	MediaType string
}

type GetMediaRow struct {
	ID            uuid.UUID
	TmdbID        int32
	Title         string
	OriginalTitle string
	PosterPath    string
	BackdropPath  string
	Overview      string
	ReleaseDate   time.Time
	Runtime       int32
	MediaType     string
	Genres        json.RawMessage
}

func (q *Queries) GetMedia(ctx context.Context, arg GetMediaParams) (GetMediaRow, error) {
	row := q.db.QueryRowContext(ctx, getMedia, arg.TmdbID, arg.MediaType)
	var i GetMediaRow
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.Title,
		&i.OriginalTitle,
		&i.PosterPath,
		&i.BackdropPath,
		&i.Overview,
		&i.ReleaseDate,
		&i.Runtime,
		&i.MediaType,
		&i.Genres,
	)
	return i, err
}
