// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type ReactionType string

const (
	ReactionTypeWatchedBecauseOfYou ReactionType = "watched_because_of_you"
	ReactionTypeGreatPick           ReactionType = "great_pick"
	ReactionTypeCurious             ReactionType = "curious"
	ReactionTypeHotTake             ReactionType = "hot_take"
)

func (e *ReactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReactionType(s)
	case string:
		*e = ReactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for ReactionType: %T", src)
	}
	return nil
}

type NullReactionType struct {
	ReactionType ReactionType
	Valid        bool // Valid is true if ReactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReactionType) Scan(value interface{}) error {
	if value == nil {
		ns.ReactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReactionType), nil
}

type SourceType string

const (
	SourceTypeSelf      SourceType = "self"
	SourceTypeFromMatch SourceType = "from_match"
)

func (e *SourceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SourceType(s)
	case string:
		*e = SourceType(s)
	default:
		return fmt.Errorf("unsupported scan type for SourceType: %T", src)
	}
	return nil
}

type NullSourceType struct {
	SourceType SourceType
	Valid      bool // Valid is true if SourceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSourceType) Scan(value interface{}) error {
	if value == nil {
		ns.SourceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SourceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSourceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SourceType), nil
}

type StatusType string

const (
	StatusTypeWatched    StatusType = "watched"
	StatusTypeNotWatched StatusType = "not_watched"
)

func (e *StatusType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatusType(s)
	case string:
		*e = StatusType(s)
	default:
		return fmt.Errorf("unsupported scan type for StatusType: %T", src)
	}
	return nil
}

type NullStatusType struct {
	StatusType StatusType
	Valid      bool // Valid is true if StatusType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatusType) Scan(value interface{}) error {
	if value == nil {
		ns.StatusType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatusType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatusType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatusType), nil
}

type Genre struct {
	ID   uuid.UUID
	Name string
}

type MediaGenre struct {
	CreatedAt time.Time
	GenreID   uuid.UUID
	MediaID   uuid.UUID
}

type Medium struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	TmdbID        int32
	Title         string
	OriginalTitle string
	PosterPath    string
	BackdropPath  string
	Overview      string
	ReleaseDate   time.Time
	Runtime       int32
	MediaType     string
}

type ReactionComment struct {
	ID         uuid.UUID
	ReactionID uuid.UUID
	UserID     uuid.UUID
	Body       string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Token struct {
	Hash   []byte
	UserID uuid.UUID
	Expiry time.Time
	Scope  string
}

type User struct {
	ID                uuid.UUID
	Name              string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	ProfilePictureUrl sql.NullString
	About             sql.NullString
	Email             string
	PasswordHash      []byte
	Activated         bool
	Version           int32
}

type UserMatch struct {
	TargetUserID       uuid.UUID
	OtherUserID        uuid.UUID
	Score              float64
	SharedMediaCount   int32
	LastRecalculatedAt time.Time
}

type UserRating struct {
	UserID      uuid.UUID
	MediaID     uuid.UUID
	RatingValue int32
	WatchedDate sql.NullTime
	DeletedAt   sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type UserReaction struct {
	ReactorUserID uuid.UUID
	RatingUserID  uuid.UUID
	MediaID       uuid.UUID
	Reaction      ReactionType
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ID            uuid.UUID
}

type UserWatchlist struct {
	UserID        uuid.UUID
	MediaID       uuid.UUID
	CreatedAt     time.Time
	Status        NullStatusType
	Source        SourceType
	SourceMatchID uuid.NullUUID
}
