// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recommendations.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getUserRecommendations = `-- name: GetUserRecommendations :many

SELECT 
  m.id,
  m.tmdb_id,
  m.title,
  m.original_title,
  m.poster_path,
  m.overview,
  m.release_date,
  m.media_type
FROM user_ratings AS ur
JOIN media AS m ON m.id = ur.media_id
WHERE ur.user_id = $1
  AND ur.deleted_at IS NULL
  AND ur.rating_value >= $2
  AND NOT EXISTS (
    SELECT 1
    FROM user_ratings AS ur_b
    WHERE ur_b.media_id = m.id
    AND ur_b.user_id = $3
    AND ur_b.deleted_at IS NULL
  )
ORDER BY ur.rating_value DESC, ur.created_at DESC, m.id DESC
LIMIT $4
`

type GetUserRecommendationsParams struct {
	TargetUserID uuid.UUID
	Threshold    int32
	UserID       uuid.UUID
	Limit        int32
}

type GetUserRecommendationsRow struct {
	ID            uuid.UUID
	TmdbID        int32
	Title         string
	OriginalTitle string
	PosterPath    string
	Overview      string
	ReleaseDate   time.Time
	MediaType     string
}

func (q *Queries) GetUserRecommendations(ctx context.Context, arg GetUserRecommendationsParams) ([]GetUserRecommendationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserRecommendations,
		arg.TargetUserID,
		arg.Threshold,
		arg.UserID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRecommendationsRow
	for rows.Next() {
		var i GetUserRecommendationsRow
		if err := rows.Scan(
			&i.ID,
			&i.TmdbID,
			&i.Title,
			&i.OriginalTitle,
			&i.PosterPath,
			&i.Overview,
			&i.ReleaseDate,
			&i.MediaType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
