// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const searchUsers = `-- name: SearchUsers :many
SELECT id,
    name,
    email,
    created_at, 
    updated_at,
    profile_picture_url,
    about
FROM users 
WHERE name ILIKE '%' || $1 || '%'
ORDER BY similarity(name, $1) DESC
LIMIT $2
`

type SearchUsersParams struct {
	Query sql.NullString
	Limit int32
}

type SearchUsersRow struct {
	ID                uuid.UUID
	Name              string
	Email             string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	ProfilePictureUrl sql.NullString
	About             sql.NullString
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, searchUsers, arg.Query, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersRow
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProfilePictureUrl,
			&i.About,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
