// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createToken = `-- name: CreateToken :exec
INSERT INTO tokens (token_hash, user_id, expiry, scope)
VALUES ($1, $2, $3, $4)
`

type CreateTokenParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	Expiry    time.Time
	Scope     string
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) error {
	_, err := q.db.ExecContext(ctx, createToken,
		arg.TokenHash,
		arg.UserID,
		arg.Expiry,
		arg.Scope,
	)
	return err
}

const deleteAllTokensAllForUser = `-- name: DeleteAllTokensAllForUser :exec
DELETE FROM tokens
WHERE scope = $1 AND user_id = $2
`

type DeleteAllTokensAllForUserParams struct {
	Scope  string
	UserID uuid.UUID
}

func (q *Queries) DeleteAllTokensAllForUser(ctx context.Context, arg DeleteAllTokensAllForUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteAllTokensAllForUser, arg.Scope, arg.UserID)
	return err
}
