// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createToken = `-- name: CreateToken :exec
INSERT INTO tokens (token_hash, user_id, expiry, scope)
VALUES ($1, $2, $3, $4)
`

type CreateTokenParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	Expiry    time.Time
	Scope     string
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) error {
	_, err := q.db.ExecContext(ctx, createToken,
		arg.TokenHash,
		arg.UserID,
		arg.Expiry,
		arg.Scope,
	)
	return err
}

const deleteAllTokensAllForUser = `-- name: DeleteAllTokensAllForUser :exec
DELETE FROM tokens
WHERE scope = $1 AND user_id = $2
`

type DeleteAllTokensAllForUserParams struct {
	Scope  string
	UserID uuid.UUID
}

func (q *Queries) DeleteAllTokensAllForUser(ctx context.Context, arg DeleteAllTokensAllForUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteAllTokensAllForUser, arg.Scope, arg.UserID)
	return err
}

const getUserFromToken = `-- name: GetUserFromToken :one
SELECT user_id, revoked_at
FROM tokens
WHERE token_hash = $1 AND scope = $2
`

type GetUserFromTokenParams struct {
	TokenHash []byte
	Scope     string
}

type GetUserFromTokenRow struct {
	UserID    uuid.UUID
	RevokedAt sql.NullTime
}

func (q *Queries) GetUserFromToken(ctx context.Context, arg GetUserFromTokenParams) (GetUserFromTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getUserFromToken, arg.TokenHash, arg.Scope)
	var i GetUserFromTokenRow
	err := row.Scan(&i.UserID, &i.RevokedAt)
	return i, err
}

const revokeAllPreviousTokens = `-- name: RevokeAllPreviousTokens :exec
UPDATE tokens
SET revoked_at = NOW()
WHERE user_id = $1 AND scope = $2
`

type RevokeAllPreviousTokensParams struct {
	UserID uuid.UUID
	Scope  string
}

func (q *Queries) RevokeAllPreviousTokens(ctx context.Context, arg RevokeAllPreviousTokensParams) error {
	_, err := q.db.ExecContext(ctx, revokeAllPreviousTokens, arg.UserID, arg.Scope)
	return err
}

const revokePreviousToken = `-- name: RevokePreviousToken :execrows
UPDATE tokens
SET revoked_at = NOW()
WHERE token_hash = $1 AND scope = $2
`

type RevokePreviousTokenParams struct {
	TokenHash []byte
	Scope     string
}

func (q *Queries) RevokePreviousToken(ctx context.Context, arg RevokePreviousTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokePreviousToken, arg.TokenHash, arg.Scope)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
