// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users_tokens.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getTokenForUser = `-- name: GetTokenForUser :one

SELECT users.id, 
      users.created_at, 
      users.name, 
      users.email, 
      users.password_hash, 
      users.activated, 
      users.version, 
      users.about,
      users.profile_picture_url
FROM users 
INNER JOIN tokens
ON users.id = tokens.user_id
WHERE tokens.token_hash = $1
AND tokens.scope = $2
AND tokens.expiry > $3
`

type GetTokenForUserParams struct {
	TokenHash []byte
	Scope     string
	Expiry    time.Time
}

type GetTokenForUserRow struct {
	ID                uuid.UUID
	CreatedAt         time.Time
	Name              string
	Email             string
	PasswordHash      []byte
	Activated         bool
	Version           int32
	About             sql.NullString
	ProfilePictureUrl sql.NullString
}

func (q *Queries) GetTokenForUser(ctx context.Context, arg GetTokenForUserParams) (GetTokenForUserRow, error) {
	row := q.db.QueryRowContext(ctx, getTokenForUser, arg.TokenHash, arg.Scope, arg.Expiry)
	var i GetTokenForUserRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Activated,
		&i.Version,
		&i.About,
		&i.ProfilePictureUrl,
	)
	return i, err
}
