// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_reactions.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const deleteUserReaction = `-- name: DeleteUserReaction :execrows
DELETE FROM user_reactions
WHERE reactor_user_id = $1 AND rating_user_id = $2 AND media_id = $3
`

type DeleteUserReactionParams struct {
	ReactorUserID uuid.UUID
	RatingUserID  uuid.UUID
	MediaID       uuid.UUID
}

func (q *Queries) DeleteUserReaction(ctx context.Context, arg DeleteUserReactionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUserReaction, arg.ReactorUserID, arg.RatingUserID, arg.MediaID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getReactionCountForRating = `-- name: GetReactionCountForRating :one
SELECT COUNT(*) AS reaction_count
FROM user_reactions
WHERE rating_user_id = $1 AND media_id = $2
`

type GetReactionCountForRatingParams struct {
	RatingUserID uuid.UUID
	MediaID      uuid.UUID
}

func (q *Queries) GetReactionCountForRating(ctx context.Context, arg GetReactionCountForRatingParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getReactionCountForRating, arg.RatingUserID, arg.MediaID)
	var reaction_count int64
	err := row.Scan(&reaction_count)
	return reaction_count, err
}

const getUserReactionsForTargetUser = `-- name: GetUserReactionsForTargetUser :many
SELECT 
  user_reactions.id,
  user_reactions.reactor_user_id,
  reactor.name AS reactor_name,
  COALESCE(reactor.profile_picture_url, '') AS reactor_profile_picture_url,
  user_reactions.rating_user_id,
  rating_user.name AS rating_user_name,
  COALESCE(rating_user.profile_picture_url, '') AS rating_user_profile_picture_url,
  user_reactions.media_id,
  media.tmdb_id,
  media.title,
  media.original_title,
  media.poster_path,
  media.backdrop_path,
  media.media_type,
  user_ratings.rating_value,
  user_ratings.watched_date,
  user_ratings.created_at AS rating_created_at,
  user_ratings.updated_at AS rating_updated_at,
  user_reactions.reaction,
  user_reactions.created_at,
  user_reactions.updated_at
FROM user_reactions
JOIN users AS reactor ON reactor.id = user_reactions.reactor_user_id
JOIN users AS rating_user ON rating_user.id = user_reactions.rating_user_id
JOIN media ON media.id = user_reactions.media_id
JOIN user_ratings
  ON user_ratings.user_id = user_reactions.rating_user_id
 AND user_ratings.media_id = user_reactions.media_id
WHERE user_reactions.rating_user_id = $1
  AND (user_reactions.created_at, user_reactions.reactor_user_id) < ($3, $4::UUID)
ORDER BY user_reactions.created_at DESC, user_reactions.reactor_user_id DESC
LIMIT $2
`

type GetUserReactionsForTargetUserParams struct {
	RatingUserID        uuid.UUID
	Limit               int32
	CursorCreatedAt     time.Time
	CursorReactorUserID uuid.UUID
}

type GetUserReactionsForTargetUserRow struct {
	ID                          uuid.UUID
	ReactorUserID               uuid.UUID
	ReactorName                 string
	ReactorProfilePictureUrl    string
	RatingUserID                uuid.UUID
	RatingUserName              string
	RatingUserProfilePictureUrl string
	MediaID                     uuid.UUID
	TmdbID                      int32
	Title                       string
	OriginalTitle               string
	PosterPath                  string
	BackdropPath                string
	MediaType                   string
	RatingValue                 int32
	WatchedDate                 sql.NullTime
	RatingCreatedAt             time.Time
	RatingUpdatedAt             time.Time
	Reaction                    ReactionType
	CreatedAt                   time.Time
	UpdatedAt                   time.Time
}

func (q *Queries) GetUserReactionsForTargetUser(ctx context.Context, arg GetUserReactionsForTargetUserParams) ([]GetUserReactionsForTargetUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserReactionsForTargetUser,
		arg.RatingUserID,
		arg.Limit,
		arg.CursorCreatedAt,
		arg.CursorReactorUserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserReactionsForTargetUserRow
	for rows.Next() {
		var i GetUserReactionsForTargetUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ReactorUserID,
			&i.ReactorName,
			&i.ReactorProfilePictureUrl,
			&i.RatingUserID,
			&i.RatingUserName,
			&i.RatingUserProfilePictureUrl,
			&i.MediaID,
			&i.TmdbID,
			&i.Title,
			&i.OriginalTitle,
			&i.PosterPath,
			&i.BackdropPath,
			&i.MediaType,
			&i.RatingValue,
			&i.WatchedDate,
			&i.RatingCreatedAt,
			&i.RatingUpdatedAt,
			&i.Reaction,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserReaction = `-- name: UpsertUserReaction :one
WITH reaction AS (
  INSERT INTO user_reactions (
    reactor_user_id,
    rating_user_id,
    media_id,
    reaction
  )
  VALUES ($1, $2, $3, $4)
  ON CONFLICT (reactor_user_id, rating_user_id, media_id)
  DO UPDATE SET
    reaction = EXCLUDED.reaction,
    updated_at = NOW()
  RETURNING id, reactor_user_id, rating_user_id, media_id, reaction, created_at, updated_at
)
SELECT
  reaction.id,
  reaction.reactor_user_id,
  reactor.name AS reactor_name,
  COALESCE(reactor.profile_picture_url, '') AS reactor_profile_picture_url,
  reaction.rating_user_id,
  rating_user.name AS rating_user_name,
  COALESCE(rating_user.profile_picture_url, '') AS rating_user_profile_picture_url,
  reaction.media_id,
  media.tmdb_id,
  media.title,
  media.original_title,
  media.poster_path,
  media.backdrop_path,
  media.media_type,
  user_ratings.rating_value,
  user_ratings.watched_date,
  user_ratings.created_at AS rating_created_at,
  user_ratings.updated_at AS rating_updated_at,
  reaction.reaction,
  reaction.created_at,
  reaction.updated_at
FROM reaction
JOIN users AS reactor ON reactor.id = reaction.reactor_user_id
JOIN users AS rating_user ON rating_user.id = reaction.rating_user_id
JOIN media ON media.id = reaction.media_id
JOIN user_ratings
  ON user_ratings.user_id = reaction.rating_user_id
 AND user_ratings.media_id = reaction.media_id
`

type UpsertUserReactionParams struct {
	ReactorUserID uuid.UUID
	RatingUserID  uuid.UUID
	MediaID       uuid.UUID
	Reaction      ReactionType
}

type UpsertUserReactionRow struct {
	ID                          uuid.UUID
	ReactorUserID               uuid.UUID
	ReactorName                 string
	ReactorProfilePictureUrl    string
	RatingUserID                uuid.UUID
	RatingUserName              string
	RatingUserProfilePictureUrl string
	MediaID                     uuid.UUID
	TmdbID                      int32
	Title                       string
	OriginalTitle               string
	PosterPath                  string
	BackdropPath                string
	MediaType                   string
	RatingValue                 int32
	WatchedDate                 sql.NullTime
	RatingCreatedAt             time.Time
	RatingUpdatedAt             time.Time
	Reaction                    ReactionType
	CreatedAt                   time.Time
	UpdatedAt                   time.Time
}

func (q *Queries) UpsertUserReaction(ctx context.Context, arg UpsertUserReactionParams) (UpsertUserReactionRow, error) {
	row := q.db.QueryRowContext(ctx, upsertUserReaction,
		arg.ReactorUserID,
		arg.RatingUserID,
		arg.MediaID,
		arg.Reaction,
	)
	var i UpsertUserReactionRow
	err := row.Scan(
		&i.ID,
		&i.ReactorUserID,
		&i.ReactorName,
		&i.ReactorProfilePictureUrl,
		&i.RatingUserID,
		&i.RatingUserName,
		&i.RatingUserProfilePictureUrl,
		&i.MediaID,
		&i.TmdbID,
		&i.Title,
		&i.OriginalTitle,
		&i.PosterPath,
		&i.BackdropPath,
		&i.MediaType,
		&i.RatingValue,
		&i.WatchedDate,
		&i.RatingCreatedAt,
		&i.RatingUpdatedAt,
		&i.Reaction,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
