// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    name,
    email,
    password_hash,
    profile_picture_url,
    about
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, name, email, created_at, updated_at, profile_picture_url, about, activated, version
`

type CreateUserParams struct {
	Name              string
	Email             string
	PasswordHash      []byte
	ProfilePictureUrl sql.NullString
	About             sql.NullString
}

type CreateUserRow struct {
	ID                uuid.UUID
	Name              string
	Email             string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	ProfilePictureUrl sql.NullString
	About             sql.NullString
	Activated         bool
	Version           int32
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.ProfilePictureUrl,
		arg.About,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfilePictureUrl,
		&i.About,
		&i.Activated,
		&i.Version,
	)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, created_at, updated_at, profile_picture_url, about, activated, version
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID                uuid.UUID
	Name              string
	Email             string
	PasswordHash      []byte
	CreatedAt         time.Time
	UpdatedAt         time.Time
	ProfilePictureUrl sql.NullString
	About             sql.NullString
	Activated         bool
	Version           int32
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfilePictureUrl,
		&i.About,
		&i.Activated,
		&i.Version,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password_hash, created_at, updated_at, profile_picture_url, about, activated, version
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID                uuid.UUID
	Name              string
	Email             string
	PasswordHash      []byte
	CreatedAt         time.Time
	UpdatedAt         time.Time
	ProfilePictureUrl sql.NullString
	About             sql.NullString
	Activated         bool
	Version           int32
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfilePictureUrl,
		&i.About,
		&i.Activated,
		&i.Version,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $1,
    email = $2,
    profile_picture_url = $3,
    about = $4,
    activated = $5,
    password_hash = $6,
    version = version + 1,
    updated_at = NOW()
WHERE id = $7 AND version = $8
RETURNING version
`

type UpdateUserParams struct {
	Name              string
	Email             string
	ProfilePictureUrl sql.NullString
	About             sql.NullString
	Activated         bool
	PasswordHash      []byte
	ID                uuid.UUID
	Version           int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.ProfilePictureUrl,
		arg.About,
		arg.Activated,
		arg.PasswordHash,
		arg.ID,
		arg.Version,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}
