// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_matches.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const checkMatchExists = `-- name: CheckMatchExists :one
SELECT EXISTS (
  SELECT 1
  FROM user_matches
  WHERE target_user_id = $1
    AND other_user_id = $2
)
`

type CheckMatchExistsParams struct {
	TargetUserID uuid.UUID
	OtherUserID  uuid.UUID
}

func (q *Queries) CheckMatchExists(ctx context.Context, arg CheckMatchExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkMatchExists, arg.TargetUserID, arg.OtherUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserMatches = `-- name: GetUserMatches :many
SELECT
  um.target_user_id,
  um.other_user_id,
  um.score,
  um.shared_media_count,
  um.last_recalculated_at,
  users.id AS user_id,
  users.name AS user_name,
  users.created_at AS user_created_at,
  users.updated_at AS user_updated_at,
  users.profile_picture_url AS user_profile_picture_url,
  users.about AS user_about
FROM user_matches AS um
INNER JOIN users
ON users.id = um.other_user_id
WHERE um.target_user_id = $1
  AND (
    $2::double precision IS NULL
    OR (
      um.score,
      um.shared_media_count,
      um.last_recalculated_at,
      um.other_user_id
    ) < (
      $2::double precision,
      $3::integer,
      $4::timestamptz,
      $5::uuid
    )
  )
ORDER BY
  um.score DESC,
  um.shared_media_count DESC,
  um.last_recalculated_at DESC,
  um.other_user_id DESC
LIMIT $6
`

type GetUserMatchesParams struct {
	TargetUserID             uuid.UUID
	CursorScore              sql.NullFloat64
	CursorSharedMediaCount   sql.NullInt32
	CursorLastRecalculatedAt sql.NullTime
	CursorOtherUserID        uuid.NullUUID
	Limit                    int32
}

type GetUserMatchesRow struct {
	TargetUserID          uuid.UUID
	OtherUserID           uuid.UUID
	Score                 float64
	SharedMediaCount      int32
	LastRecalculatedAt    time.Time
	UserID                uuid.UUID
	UserName              string
	UserCreatedAt         time.Time
	UserUpdatedAt         time.Time
	UserProfilePictureUrl sql.NullString
	UserAbout             sql.NullString
}

func (q *Queries) GetUserMatches(ctx context.Context, arg GetUserMatchesParams) ([]GetUserMatchesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserMatches,
		arg.TargetUserID,
		arg.CursorScore,
		arg.CursorSharedMediaCount,
		arg.CursorLastRecalculatedAt,
		arg.CursorOtherUserID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserMatchesRow
	for rows.Next() {
		var i GetUserMatchesRow
		if err := rows.Scan(
			&i.TargetUserID,
			&i.OtherUserID,
			&i.Score,
			&i.SharedMediaCount,
			&i.LastRecalculatedAt,
			&i.UserID,
			&i.UserName,
			&i.UserCreatedAt,
			&i.UserUpdatedAt,
			&i.UserProfilePictureUrl,
			&i.UserAbout,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserMatch = `-- name: UpsertUserMatch :execrows
INSERT INTO user_matches (
  target_user_id,
  other_user_id,
  score,
  shared_media_count
) VALUES ($1, $2, $3, $4)
ON CONFLICT (target_user_id, other_user_id)
DO UPDATE SET 
  score = EXCLUDED.score, 
  shared_media_count = EXCLUDED.shared_media_count,
  last_recalculated_at = NOW()
`

type UpsertUserMatchParams struct {
	TargetUserID     uuid.UUID
	OtherUserID      uuid.UUID
	Score            float64
	SharedMediaCount int32
}

func (q *Queries) UpsertUserMatch(ctx context.Context, arg UpsertUserMatchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertUserMatch,
		arg.TargetUserID,
		arg.OtherUserID,
		arg.Score,
		arg.SharedMediaCount,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
