// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_watchlist.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteMediaFromWatchlist = `-- name: DeleteMediaFromWatchlist :execrows

DELETE FROM user_watchlist
WHERE user_id = $1 AND media_id = $2
`

type DeleteMediaFromWatchlistParams struct {
	UserID  uuid.UUID
	MediaID uuid.UUID
}

func (q *Queries) DeleteMediaFromWatchlist(ctx context.Context, arg DeleteMediaFromWatchlistParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMediaFromWatchlist, arg.UserID, arg.MediaID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAllItemsInWatchlist = `-- name: GetAllItemsInWatchlist :many

SELECT
  uw.user_id,
  uw.media_id,
  uw.source,
  uw.source_match_id,
  uw.created_at,
  uw.status,
  m.tmdb_id,
  m.title,
  m.original_title,
  m.poster_path,
  m.backdrop_path,
  m.overview,
  m.release_date,
  m.runtime,
  m.media_type
FROM user_watchlist AS uw
JOIN media AS m
ON uw.media_id = m.id
WHERE uw.user_id = $1
  AND (
    $3::timestamptz = '0001-01-01 00:00:00+00'::timestamptz
    OR (uw.created_at, uw.media_id) < ($3, $4::UUID)
  )
ORDER BY uw.created_at DESC, uw.media_id DESC
LIMIT $2
`

type GetAllItemsInWatchlistParams struct {
	UserID          uuid.UUID
	Limit           int32
	CursorCreatedAt time.Time
	CursorMediaID   uuid.UUID
}

type GetAllItemsInWatchlistRow struct {
	UserID        uuid.UUID
	MediaID       uuid.UUID
	Source        SourceType
	SourceMatchID uuid.NullUUID
	CreatedAt     time.Time
	Status        NullStatusType
	TmdbID        int32
	Title         string
	OriginalTitle string
	PosterPath    string
	BackdropPath  string
	Overview      string
	ReleaseDate   time.Time
	Runtime       int32
	MediaType     string
}

func (q *Queries) GetAllItemsInWatchlist(ctx context.Context, arg GetAllItemsInWatchlistParams) ([]GetAllItemsInWatchlistRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllItemsInWatchlist,
		arg.UserID,
		arg.Limit,
		arg.CursorCreatedAt,
		arg.CursorMediaID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllItemsInWatchlistRow
	for rows.Next() {
		var i GetAllItemsInWatchlistRow
		if err := rows.Scan(
			&i.UserID,
			&i.MediaID,
			&i.Source,
			&i.SourceMatchID,
			&i.CreatedAt,
			&i.Status,
			&i.TmdbID,
			&i.Title,
			&i.OriginalTitle,
			&i.PosterPath,
			&i.BackdropPath,
			&i.Overview,
			&i.ReleaseDate,
			&i.Runtime,
			&i.MediaType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMediaToWatchlist = `-- name: InsertMediaToWatchlist :one

INSERT INTO user_watchlist (
  user_id,
  media_id,
  source,
  source_match_id
) VALUES ($1, $2, $3, $4)
RETURNING user_id, media_id, source, source_match_id, created_at, status
`

type InsertMediaToWatchlistParams struct {
	UserID        uuid.UUID
	MediaID       uuid.UUID
	Source        SourceType
	SourceMatchID uuid.NullUUID
}

type InsertMediaToWatchlistRow struct {
	UserID        uuid.UUID
	MediaID       uuid.UUID
	Source        SourceType
	SourceMatchID uuid.NullUUID
	CreatedAt     time.Time
	Status        NullStatusType
}

func (q *Queries) InsertMediaToWatchlist(ctx context.Context, arg InsertMediaToWatchlistParams) (InsertMediaToWatchlistRow, error) {
	row := q.db.QueryRowContext(ctx, insertMediaToWatchlist,
		arg.UserID,
		arg.MediaID,
		arg.Source,
		arg.SourceMatchID,
	)
	var i InsertMediaToWatchlistRow
	err := row.Scan(
		&i.UserID,
		&i.MediaID,
		&i.Source,
		&i.SourceMatchID,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const updateWatchlistItemStatus = `-- name: UpdateWatchlistItemStatus :one

UPDATE user_watchlist
SET status = $3
WHERE user_id = $1 AND media_id = $2
RETURNING user_id, media_id, source, source_match_id, created_at, status
`

type UpdateWatchlistItemStatusParams struct {
	UserID  uuid.UUID
	MediaID uuid.UUID
	Status  NullStatusType
}

type UpdateWatchlistItemStatusRow struct {
	UserID        uuid.UUID
	MediaID       uuid.UUID
	Source        SourceType
	SourceMatchID uuid.NullUUID
	CreatedAt     time.Time
	Status        NullStatusType
}

func (q *Queries) UpdateWatchlistItemStatus(ctx context.Context, arg UpdateWatchlistItemStatusParams) (UpdateWatchlistItemStatusRow, error) {
	row := q.db.QueryRowContext(ctx, updateWatchlistItemStatus, arg.UserID, arg.MediaID, arg.Status)
	var i UpdateWatchlistItemStatusRow
	err := row.Scan(
		&i.UserID,
		&i.MediaID,
		&i.Source,
		&i.SourceMatchID,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}
