// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_reactions.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteUserReaction = `-- name: DeleteUserReaction :execrows
DELETE FROM user_reactions
WHERE reactor_user_id = $1 AND rating_user_id = $2 AND media_id = $3
`

type DeleteUserReactionParams struct {
	ReactorUserID uuid.UUID
	RatingUserID  uuid.UUID
	MediaID       uuid.UUID
}

func (q *Queries) DeleteUserReaction(ctx context.Context, arg DeleteUserReactionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUserReaction, arg.ReactorUserID, arg.RatingUserID, arg.MediaID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getReactionCountForRating = `-- name: GetReactionCountForRating :one
SELECT COUNT(*) AS reaction_count
FROM user_reactions
WHERE rating_user_id = $1 AND media_id = $2
`

type GetReactionCountForRatingParams struct {
	RatingUserID uuid.UUID
	MediaID      uuid.UUID
}

func (q *Queries) GetReactionCountForRating(ctx context.Context, arg GetReactionCountForRatingParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getReactionCountForRating, arg.RatingUserID, arg.MediaID)
	var reaction_count int64
	err := row.Scan(&reaction_count)
	return reaction_count, err
}

const getUserReactionsForTargetUser = `-- name: GetUserReactionsForTargetUser :many
SELECT 
  id,
  reactor_user_id,
  rating_user_id,
  media_id,
  reaction,
  created_at,
  updated_at
FROM user_reactions
WHERE rating_user_id = $1
  AND (created_at, reactor_user_id) < ($3, $4::UUID)
ORDER BY created_at DESC, reactor_user_id DESC
LIMIT $2
`

type GetUserReactionsForTargetUserParams struct {
	RatingUserID        uuid.UUID
	Limit               int32
	CursorCreatedAt     time.Time
	CursorReactorUserID uuid.UUID
}

type GetUserReactionsForTargetUserRow struct {
	ID            uuid.UUID
	ReactorUserID uuid.UUID
	RatingUserID  uuid.UUID
	MediaID       uuid.UUID
	Reaction      ReactionType
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetUserReactionsForTargetUser(ctx context.Context, arg GetUserReactionsForTargetUserParams) ([]GetUserReactionsForTargetUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserReactionsForTargetUser,
		arg.RatingUserID,
		arg.Limit,
		arg.CursorCreatedAt,
		arg.CursorReactorUserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserReactionsForTargetUserRow
	for rows.Next() {
		var i GetUserReactionsForTargetUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ReactorUserID,
			&i.RatingUserID,
			&i.MediaID,
			&i.Reaction,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserReaction = `-- name: UpsertUserReaction :one
INSERT INTO user_reactions (
  reactor_user_id,
  rating_user_id,
  media_id,
  reaction
)
VALUES ($1, $2, $3, $4)
ON CONFLICT (reactor_user_id, rating_user_id, media_id)
DO UPDATE SET
  reaction = EXCLUDED.reaction,
  updated_at = NOW()
RETURNING id, reactor_user_id, rating_user_id, media_id, reaction, created_at, updated_at
`

type UpsertUserReactionParams struct {
	ReactorUserID uuid.UUID
	RatingUserID  uuid.UUID
	MediaID       uuid.UUID
	Reaction      ReactionType
}

type UpsertUserReactionRow struct {
	ID            uuid.UUID
	ReactorUserID uuid.UUID
	RatingUserID  uuid.UUID
	MediaID       uuid.UUID
	Reaction      ReactionType
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) UpsertUserReaction(ctx context.Context, arg UpsertUserReactionParams) (UpsertUserReactionRow, error) {
	row := q.db.QueryRowContext(ctx, upsertUserReaction,
		arg.ReactorUserID,
		arg.RatingUserID,
		arg.MediaID,
		arg.Reaction,
	)
	var i UpsertUserReactionRow
	err := row.Scan(
		&i.ID,
		&i.ReactorUserID,
		&i.RatingUserID,
		&i.MediaID,
		&i.Reaction,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
