// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_ratings.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getAllRatingsForSingleMedia = `-- name: GetAllRatingsForSingleMedia :many
SELECT
  ur.user_id,
  ur.media_id,
  ur.rating_value,
  ur.watched_date,
  ur.created_at,
  ur.updated_at,
  m.title,
  m.overview,
  m.poster_path,
  m.release_date,
  m.tmdb_id,
  m.backdrop_path,
  m.runtime,
  m.media_type
FROM media AS m
JOIN user_ratings AS ur
ON m.id = ur.media_id
WHERE media_id = $1
  AND ur.deleted_at IS NULL
  AND (ur.created_at, ur.user_id) < ($3, $4::UUID)
ORDER BY ur.created_at DESC, ur.user_id DESC
LIMIT $2
`

type GetAllRatingsForSingleMediaParams struct {
	MediaID         uuid.UUID
	Limit           int32
	CursorCreatedAt time.Time
	CursorUserID    uuid.UUID
}

type GetAllRatingsForSingleMediaRow struct {
	UserID       uuid.UUID
	MediaID      uuid.UUID
	RatingValue  int32
	WatchedDate  sql.NullTime
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Title        string
	Overview     string
	PosterPath   string
	ReleaseDate  time.Time
	TmdbID       int32
	BackdropPath string
	Runtime      int32
	MediaType    string
}

func (q *Queries) GetAllRatingsForSingleMedia(ctx context.Context, arg GetAllRatingsForSingleMediaParams) ([]GetAllRatingsForSingleMediaRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllRatingsForSingleMedia,
		arg.MediaID,
		arg.Limit,
		arg.CursorCreatedAt,
		arg.CursorUserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllRatingsForSingleMediaRow
	for rows.Next() {
		var i GetAllRatingsForSingleMediaRow
		if err := rows.Scan(
			&i.UserID,
			&i.MediaID,
			&i.RatingValue,
			&i.WatchedDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Overview,
			&i.PosterPath,
			&i.ReleaseDate,
			&i.TmdbID,
			&i.BackdropPath,
			&i.Runtime,
			&i.MediaType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUserRatings = `-- name: GetAllUserRatings :many
SELECT
    user_ratings.user_id,
    user_ratings.rating_value,
    user_ratings.media_id
FROM user_ratings
JOIN users ON user_ratings.user_id = users.id
WHERE user_ratings.user_id = $1
`

type GetAllUserRatingsRow struct {
	UserID      uuid.UUID
	RatingValue int32
	MediaID     uuid.UUID
}

func (q *Queries) GetAllUserRatings(ctx context.Context, userID uuid.UUID) ([]GetAllUserRatingsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUserRatings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUserRatingsRow
	for rows.Next() {
		var i GetAllUserRatingsRow
		if err := rows.Scan(&i.UserID, &i.RatingValue, &i.MediaID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSingleUserRating = `-- name: GetSingleUserRating :one
SELECT 
  u.user_id, 
  u.media_id, 
  u.rating_value, 
  u.watched_date, 
  u.created_at, 
  u.updated_at,
  m.title,
  m.overview,
  m.poster_path,
  m.release_date,
  m.media_type
FROM user_ratings AS u
JOIN media AS m
ON u.media_id = m.id
WHERE u.user_id = $1 AND u.media_id = $2 AND u.deleted_at IS NULL
`

type GetSingleUserRatingParams struct {
	UserID  uuid.UUID
	MediaID uuid.UUID
}

type GetSingleUserRatingRow struct {
	UserID      uuid.UUID
	MediaID     uuid.UUID
	RatingValue int32
	WatchedDate sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Overview    string
	PosterPath  string
	ReleaseDate time.Time
	MediaType   string
}

func (q *Queries) GetSingleUserRating(ctx context.Context, arg GetSingleUserRatingParams) (GetSingleUserRatingRow, error) {
	row := q.db.QueryRowContext(ctx, getSingleUserRating, arg.UserID, arg.MediaID)
	var i GetSingleUserRatingRow
	err := row.Scan(
		&i.UserID,
		&i.MediaID,
		&i.RatingValue,
		&i.WatchedDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Overview,
		&i.PosterPath,
		&i.ReleaseDate,
		&i.MediaType,
	)
	return i, err
}

const getUsersRatings = `-- name: GetUsersRatings :many

SELECT 
  u.user_id, 
  u.media_id, 
  u.rating_value, 
  u.watched_date, 
  u.created_at, 
  u.updated_at,
  m.title,
  m.overview,
  m.poster_path,
  m.release_date,
  m.media_type
FROM user_ratings AS u
JOIN media AS m
ON u.media_id = m.id
WHERE u.user_id = $1
  AND u.deleted_at IS NULL
  AND (u.created_at, u.media_id) < ($3, $4::UUID)
ORDER BY u.created_at DESC, u.media_id DESC
LIMIT $2
`

type GetUsersRatingsParams struct {
	UserID          uuid.UUID
	Limit           int32
	CursorCreatedAt time.Time
	CursorMediaID   uuid.UUID
}

type GetUsersRatingsRow struct {
	UserID      uuid.UUID
	MediaID     uuid.UUID
	RatingValue int32
	WatchedDate sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Overview    string
	PosterPath  string
	ReleaseDate time.Time
	MediaType   string
}

func (q *Queries) GetUsersRatings(ctx context.Context, arg GetUsersRatingsParams) ([]GetUsersRatingsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsersRatings,
		arg.UserID,
		arg.Limit,
		arg.CursorCreatedAt,
		arg.CursorMediaID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersRatingsRow
	for rows.Next() {
		var i GetUsersRatingsRow
		if err := rows.Scan(
			&i.UserID,
			&i.MediaID,
			&i.RatingValue,
			&i.WatchedDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Overview,
			&i.PosterPath,
			&i.ReleaseDate,
			&i.MediaType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUserRating = `-- name: SoftDeleteUserRating :execrows

UPDATE user_ratings
SET deleted_at = NOW(), updated_at = NOW()
WHERE user_id = $1 AND media_id = $2 AND deleted_at IS NULL
`

type SoftDeleteUserRatingParams struct {
	UserID  uuid.UUID
	MediaID uuid.UUID
}

func (q *Queries) SoftDeleteUserRating(ctx context.Context, arg SoftDeleteUserRatingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteUserRating, arg.UserID, arg.MediaID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertUserRating = `-- name: UpsertUserRating :one

INSERT INTO user_ratings (
  user_id,
  media_id,
  rating_value,
  watched_date
) VALUES ($1, $2, $3, $4) 
ON CONFLICT (user_id, media_id)
DO UPDATE SET 
  rating_value = EXCLUDED.rating_value, 
  watched_date = EXCLUDED.watched_date,
  deleted_at = NULL,
  updated_at = NOW()
RETURNING user_id, media_id, rating_value, watched_date, created_at, updated_at
`

type UpsertUserRatingParams struct {
	UserID      uuid.UUID
	MediaID     uuid.UUID
	RatingValue int32
	WatchedDate sql.NullTime
}

type UpsertUserRatingRow struct {
	UserID      uuid.UUID
	MediaID     uuid.UUID
	RatingValue int32
	WatchedDate sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) UpsertUserRating(ctx context.Context, arg UpsertUserRatingParams) (UpsertUserRatingRow, error) {
	row := q.db.QueryRowContext(ctx, upsertUserRating,
		arg.UserID,
		arg.MediaID,
		arg.RatingValue,
		arg.WatchedDate,
	)
	var i UpsertUserRatingRow
	err := row.Scan(
		&i.UserID,
		&i.MediaID,
		&i.RatingValue,
		&i.WatchedDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
