// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (
  created_at, 
  updated_at, 
  tmdb_id, 
  title, 
  original_title, 
  poster_path, 
  backdrop_path, 
  overview, 
  release_date, 
  runtime, 
  media_type
) 
VALUES (
  NOW(), NOW(), $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, created_at, updated_at, tmdb_id, title, original_title, poster_path, backdrop_path, overview, release_date, runtime, media_type
`

type CreateMediaParams struct {
	TmdbID        int32
	Title         string
	OriginalTitle string
	PosterPath    string
	BackdropPath  string
	Overview      string
	ReleaseDate   time.Time
	Runtime       int32
	MediaType     string
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRowContext(ctx, createMedia,
		arg.TmdbID,
		arg.Title,
		arg.OriginalTitle,
		arg.PosterPath,
		arg.BackdropPath,
		arg.Overview,
		arg.ReleaseDate,
		arg.Runtime,
		arg.MediaType,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TmdbID,
		&i.Title,
		&i.OriginalTitle,
		&i.PosterPath,
		&i.BackdropPath,
		&i.Overview,
		&i.ReleaseDate,
		&i.Runtime,
		&i.MediaType,
	)
	return i, err
}

const createMediaGenre = `-- name: CreateMediaGenre :exec
INSERT INTO media_genres (
    created_at,
    genre_id,
    media_id
) VALUES (
    NOW(), $1, $2
)
`

type CreateMediaGenreParams struct {
	GenreID uuid.UUID
	MediaID uuid.UUID
}

func (q *Queries) CreateMediaGenre(ctx context.Context, arg CreateMediaGenreParams) error {
	_, err := q.db.ExecContext(ctx, createMediaGenre, arg.GenreID, arg.MediaID)
	return err
}

const getAllRatingsForSingleMedia = `-- name: GetAllRatingsForSingleMedia :many
SELECT 
  ur.user_id, 
  ur.media_id, 
  ur.rating_value, 
  ur.watched_date, 
  ur.created_at, 
  ur.updated_at,
  m.title,
  m.overview,
  m.poster_path,
  m.release_date,
  m.tmdb_id,
  m.backdrop_path,
  m.runtime,
  m.media_type
FROM media AS m
JOIN user_ratings AS ur
ON m.id = ur.media_id
WHERE media_id = $1
  AND ur.deleted_at IS NULL
  AND (ur.created_at, ur.user_id) < ($3, $4::UUID)
ORDER BY ur.created_at DESC, ur.user_id DESC
LIMIT $2
`

type GetAllRatingsForSingleMediaParams struct {
	MediaID         uuid.UUID
	Limit           int32
	CursorCreatedAt time.Time
	CursorUserID    uuid.UUID
}

type GetAllRatingsForSingleMediaRow struct {
	UserID       uuid.UUID
	MediaID      uuid.UUID
	RatingValue  int32
	WatchedDate  sql.NullTime
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Title        string
	Overview     string
	PosterPath   string
	ReleaseDate  time.Time
	TmdbID       int32
	BackdropPath string
	Runtime      int32
	MediaType    string
}

func (q *Queries) GetAllRatingsForSingleMedia(ctx context.Context, arg GetAllRatingsForSingleMediaParams) ([]GetAllRatingsForSingleMediaRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllRatingsForSingleMedia,
		arg.MediaID,
		arg.Limit,
		arg.CursorCreatedAt,
		arg.CursorUserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllRatingsForSingleMediaRow
	for rows.Next() {
		var i GetAllRatingsForSingleMediaRow
		if err := rows.Scan(
			&i.UserID,
			&i.MediaID,
			&i.RatingValue,
			&i.WatchedDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Overview,
			&i.PosterPath,
			&i.ReleaseDate,
			&i.TmdbID,
			&i.BackdropPath,
			&i.Runtime,
			&i.MediaType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGenre = `-- name: GetGenre :one
SELECT id
FROM genres
WHERE name = $1
`

func (q *Queries) GetGenre(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getGenre, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getMedia = `-- name: GetMedia :one

SELECT  media.id,
        media.tmdb_id,
        media.title,
        media.original_title,
        media.poster_path,
        media.backdrop_path,
        media.overview,
        media.release_date,
        media.runtime,
        media.media_type,
        (
            SELECT json_agg(genres.name)
            FROM genres
            JOIN media_genres ON genres.id = media_genres.genre_id
            WHERE media_genres.media_id = media.id
        ) AS genres
FROM media
WHERE media.tmdb_id = $1 AND media.media_type = $2
`

type GetMediaParams struct {
	TmdbID    int32
	MediaType string
}

type GetMediaRow struct {
	ID            uuid.UUID
	TmdbID        int32
	Title         string
	OriginalTitle string
	PosterPath    string
	BackdropPath  string
	Overview      string
	ReleaseDate   time.Time
	Runtime       int32
	MediaType     string
	Genres        json.RawMessage
}

func (q *Queries) GetMedia(ctx context.Context, arg GetMediaParams) (GetMediaRow, error) {
	row := q.db.QueryRowContext(ctx, getMedia, arg.TmdbID, arg.MediaType)
	var i GetMediaRow
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.Title,
		&i.OriginalTitle,
		&i.PosterPath,
		&i.BackdropPath,
		&i.Overview,
		&i.ReleaseDate,
		&i.Runtime,
		&i.MediaType,
		&i.Genres,
	)
	return i, err
}
