// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Genre struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}

type Movie struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ImdbID      string
	Title       string
	PosterPath  string
	YoutubeID   string
	AdminReview string
	RatingValue int16
	RatingName  string
}

type MovieGenre struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	GenreID   uuid.UUID
	MovieID   uuid.UUID
}
