// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Genre struct {
	ID   uuid.UUID
	Name string
}

type MediaGenre struct {
	CreatedAt time.Time
	GenreID   uuid.UUID
	MediaID   uuid.UUID
}

type Medium struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	TmdbID        int32
	Title         string
	OriginalTitle string
	PosterPath    string
	BackdropPath  string
	Overview      string
	ReleaseDate   time.Time
	Runtime       int32
	MediaType     string
}
