// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: movies.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getMovie = `-- name: GetMovie :one

SELECT id, created_at, updated_at, imdb_id, title, poster_path, youtube_id, admin_review, rating_value, rating_name
FROM movies
WHERE $1 = id
`

func (q *Queries) GetMovie(ctx context.Context, id uuid.UUID) (Movie, error) {
	row := q.db.QueryRowContext(ctx, getMovie, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImdbID,
		&i.Title,
		&i.PosterPath,
		&i.YoutubeID,
		&i.AdminReview,
		&i.RatingValue,
		&i.RatingName,
	)
	return i, err
}

const getMovies = `-- name: GetMovies :many

SELECT id, created_at, updated_at, imdb_id, title, poster_path, youtube_id, admin_review, rating_value, rating_name
FROM movies
ORDER BY created_at
`

func (q *Queries) GetMovies(ctx context.Context) ([]Movie, error) {
	rows, err := q.db.QueryContext(ctx, getMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImdbID,
			&i.Title,
			&i.PosterPath,
			&i.YoutubeID,
			&i.AdminReview,
			&i.RatingValue,
			&i.RatingName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
