// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_matches.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const upsertUserMatch = `-- name: UpsertUserMatch :execrows
INSERT INTO user_matches (
  target_user_id,
  other_user_id,
  score,
  shared_media_count
) VALUES ($1, $2, $3, $4)
ON CONFLICT (target_user_id, other_user_id)
DO UPDATE SET 
  score = EXCLUDED.score, 
  shared_media_count = EXCLUDED.shared_media_count,
  last_recalculated_at = NOW()
`

type UpsertUserMatchParams struct {
	TargetUserID     uuid.UUID
	OtherUserID      uuid.UUID
	Score            float64
	SharedMediaCount int32
}

func (q *Queries) UpsertUserMatch(ctx context.Context, arg UpsertUserMatchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertUserMatch,
		arg.TargetUserID,
		arg.OtherUserID,
		arg.Score,
		arg.SharedMediaCount,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
